npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma01.source -O IDATEN01 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma02.source -O IDATEN02 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma03.source -O IDATEN03 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma04.source -O IDATEN04 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma05.source -O IDATEN05 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma06.source -O IDATEN06 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma07.source -O IDATEN07 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma08.source -O IDATEN08 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma09.source -O IDATEN09 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma10.source -O IDATEN10 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma11.source -O IDATEN11 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma12.source -O IDATEN12 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma13.source -O IDATEN13 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma14.source -O IDATEN14 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma15.source -O IDATEN15 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma16.source -O IDATEN16 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma17.source -O IDATEN17 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN.detector -E /home/jlee/NPTools/NPTools_IDATEN/asdf/gamma18.source -O IDATEN18 -B /home/jlee/NPTools/NPTools_IDATEN/asdf/batch.mac &
