npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma01.source -O IDATEN01 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma02.source -O IDATEN02 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma03.source -O IDATEN03 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma04.source -O IDATEN04 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma05.source -O IDATEN05 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma06.source -O IDATEN06 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma07.source -O IDATEN07 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma08.source -O IDATEN08 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma09.source -O IDATEN09 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma10.source -O IDATEN10 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma11.source -O IDATEN11 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma12.source -O IDATEN12 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma13.source -O IDATEN13 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma14.source -O IDATEN14 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma15.source -O IDATEN15 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma16.source -O IDATEN16 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma17.source -O IDATEN17 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma18.source -O IDATEN18 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma19.source -O IDATEN19 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma20.source -O IDATEN20 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma21.source -O IDATEN21 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma22.source -O IDATEN22 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma23.source -O IDATEN23 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma24.source -O IDATEN24 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma25.source -O IDATEN25 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma26.source -O IDATEN26 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma27.source -O IDATEN27 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma28.source -O IDATEN28 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma29.source -O IDATEN29 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma30.source -O IDATEN30 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma31.source -O IDATEN31 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma32.source -O IDATEN32 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma33.source -O IDATEN33 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma34.source -O IDATEN34 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma35.source -O IDATEN35 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma36.source -O IDATEN36 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma37.source -O IDATEN37 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma38.source -O IDATEN38 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma39.source -O IDATEN39 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
npsimulation -D IDATEN_Tig.detector -E /home/jlee/NPTools/test/NPTool_IDATEN/asdf/gamma40.source -O IDATEN40 -B /home/jlee/NPTools/test/NPTool_IDATEN/asdf/batch.mac &
